### PR TITLE
Removing OPTIONS version negotiation

### PR DESCRIPTION
**Pull request by thekaveman**
Proposing changes for the issue outlined in https://github.com/openmobilityfoundation/mobility-data-specification/issues/510.

Targeting the Reconciliation branch as much has moved/changed and this helps avoid conflicts.

### CODE REVIEW

**Review by marie-x — COMMENTED** [review]
Seems legit.  Will wait til you un-tag draft to approve.

**Comment by thekaveman** [comment]
Yep, wanted to mark as Draft to give the wider OMF/MDS community a chance to see it before it went in to Reconciliation. Also a bit weird that the PR is over here in this fork, but alas, avoiding merge conflicts is easier if done from the start!

**Comment by jrheard** [comment]
looks good to me! :)

**Comment by janedotx** [comment]
A couple thoughts:
1. I'm not sure we want to remove this for every single service.
2. My understanding is that this HTTP verb is meant to facilitate version discovery. If the server prefers version 3.0 but _could_ serve 2.0, the client could still use 2.0.

**Comment by thekaveman** [comment]
Closing in favor of openmobilityfoundation#536

**Pull request closed without merging**
